---
title: "CaseStudy1"
author: "Anish Patel"
date: "2/22/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	comment = NULL
)
library(tidyverse)
library(maps)
library(mapproj)
```



```{r}
Breweries <- read_csv("Breweries.csv")
library(ggmap)
library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)
library(openintro)
library(plotly)
library(billboarder)
library(vctrs)
```

## Question 1 - How many Brewereries are in Each State?

```{r}

dat = Breweries

#obtain the count of the number of breweres by state arranged in decending order
state_count = dat %>% group_by(State) %>% count() %>% arrange(-n)


```

## Bar Chart of Brewery Count by State

```{r}

billboarder() %>%
  bb_barchart(state_count) %>%
  bb_labs(title = "Count of Breweries by State")
```

## Heatmap

```{r}
#Here we are creating heatmap to show quanties. 
heat_map = ggplot(data = states) + 
  geom_polygon(aes(x = long, y = lat, fill = n, group = group), color = "white") + 
  coord_fixed(1.3) +
  scale_fill_gradientn(colours = rev(heat.colors(10)),na.value = "grey90",
                       guide = guide_colourbar(barwidth = 5, barheight = 0.4,
                                               #put legend title on top of legend
                                               title.position = "top")) + 
  labs(title = "Count of Breweries by State (Continental US)")
  
ggplotly(heat_map)

  
```

## Question 2 - Merge data by Brew ID, and check first 6 and last 6 obs.

```{r}

#rename col to match Brewery Data set
colnames(Beers)[5]="Brew_ID"

#merge data by Brew_ID 
final=merge(Beers,Breweries,by=c("Brew_ID"))

head(final,n=6)
tail(final,n=6)

```

## Question 3 - How to deal with Missing Values
```{r}

#Of the missing values, 1005 are missing for "IBU", 5 missing values for "Style"", and 62 missing values for ABV, and 1,005 missing values for IBU.  


#One method would be to omit the observations with missing data which isn't ideal since we will lose quite a few observations

nabeers=na.omit(final)

#The other method would be to impute the median values of the variable to the missing variables.

#Find Medians of Style, IBU, and ABV

```

##Question 4 - 